# Generated by Django 5.0.2 on 2024-03-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_image_maskremovalmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskremovalmodel',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='MaskRemovalModel',
        ),
    ]
